feat: Encourage developers to use DLLs for devPlugins
goatcorp/Dalamud pull request #1958
Opened 2024-07-22 14:46 UTC by NotNite

Discussed [here](https://canary.discord.com/channels/581875019861328007/860813266468732938/1264949160357134458).

Adds a button to pick a .dll for the dev plugin path, as well as removes the directory scan logic. While directory search hasn't been encouraged for a while now, there may still be people who use it, so this probably is gonna break someone's workflow.

![image](https://github.com/user-attachments/assets/dc160d54-1574-4861-9e61-e6a93eec4d82)

2024-07-22 14:56 UTC, Haselnussbomber commented
Text above the plugin needs to be updated. Still says can be either directory or dll path.

2024-07-22 14:57 UTC, NotNite commented
> Text above the plugin needs to be updated. Still says can be either directory or dll path.

I'm blind

2024-07-22 14:59 UTC, Haselnussbomber commented
Sorry meant button, not plugin. But you got it. 👍

2024-07-22 15:36 UTC, KazWolfe commented
Can we change this such that dev plugins are still loaded in recursively but only individual paths can be saved for now?

If so, we can deprecate that load behavior in API 11 and get a proper announcement out to everyone.

2024-09-13 05:37 UTC, KazWolfe requested changes

2024-09-13 05:37 UTC, KazWolfe commented on Dalamud/Plugin/Internal/PluginManager.cs
> -            else if (File.Exists(setting.Path))
For now, let's keep the recursive loading mode but just block setting folders in UI.

Removing this behavior should be an api11 todo so we have time to announce it.

2024-09-13 05:37 UTC, KazWolfe commented on Dalamud/Interface/Internal/Windows/Settings/Widgets/DevPluginsSettingsEntry.cs
> +        var locationSelect = Loc.Localize("DalamudDevPluginLocationSelect", "Select Dev Plugin Location");
Please change this label to `Select DLL` or similar.

2024-11-12 16:25 UTC, KazWolfe commented on Dalamud/Interface/Internal/Windows/Settings/Widgets/DevPluginsSettingsEntry.cs
> +        var locationSelect = Loc.Localize("DalamudDevPluginLocationSelect", "Select Dev Plugin Location");
```suggestion
        var locationSelect = Loc.Localize("DalamudDevPluginLocationSelect", "Select Dev Plugin DLL");
```

2024-11-12 16:27 UTC, merged