Gauge update (please test /xldata gauge pane)
goatcorp/Dalamud pull request #698
Opened 2021-12-05 17:14 UTC by daemitus

SMN rework, AST tweak.

Please test the /xldata gauge pane before merging. I didn't have a change before the queue went to 1700 again.

2021-12-05 17:17 UTC, goaaats requested changes

2021-12-05 17:17 UTC, goaaats commented on Dalamud/Interface/Internal/Windows/DataWindow.cs
> +            var props = gauge.GetType().GetProperties();
You can do Util.DumpObject() here

2021-12-05 17:24 UTC, daemitus commented
Think we're good now

2021-12-05 17:26 UTC, goaaats submitted a review, later dismissed

2021-12-05 22:19 UTC, daemitus commented
Safely use GetType

2021-12-06 04:58 UTC, goaaats approved these changes

2021-12-06 04:58 UTC, merged